# Generated by Django 4.2.3 on 2023-08-14 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dictionaries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True, verbose_name='id address')),
                ('location', models.CharField(blank=True, max_length=300, null=True, verbose_name='location')),
                ('cabinet', models.CharField(blank=True, max_length=5, null=True, verbose_name='cabinet')),
                ('employee', models.CharField(blank=True, max_length=255, null=True, verbose_name='employee')),
                ('remote_admin_url', models.URLField(blank=True, null=True, verbose_name='remote admin url')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dictionaries.department', verbose_name='department')),
                ('management', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dictionaries.management', verbose_name='management')),
                ('type_of_device', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dictionaries.typeofdevice', verbose_name='type of device')),
            ],
            options={
                'verbose_name': 'device',
                'verbose_name_plural': 'devices',
                'ordering': ('ip',),
            },
        ),
    ]
